SELECT DISTINCT(codprod),ST,SITTRIBUT,baseicms,baseicst,ALIQICST,codplpag,percipi,pericm,percst,vlbaseipi,vlipi,
PERICMSANTECIPADO,numlanccp,codfiscal,codst,perpis,VLCREDPIS,VLCREDICMS,PERICMFRETE,CODFUNCREQ,VLDESCICMISENCAO,CUSTOREALSEMST,
IVA,ALIQICMS1,ALIQICMS2,CUSTOFINEST
FROM PCMOV
WHERE DTMOV > '01-jan-2023'
